export type ProfileStackParamList = {
  ProfileMain: undefined;
  PersonalInfo: undefined;
  Wallet: undefined;
  About: undefined;
  Notifications: undefined;
  ConfigureNotifications: undefined;
  Dependents: undefined;
  DependentDetail: { dependentId: string };
  AddDependent: undefined;
  DependentSuccess: undefined;
  Conversations: undefined;
  AddPaymentMethod: undefined;
  AddCard: { paymentType: 'credit' | 'debit' };
  CardRegisteredSuccess: undefined;
  TermsOfUse: undefined;
  PrivacyPolicy: undefined;
  CancellationPolicy: undefined;
  EditName: undefined;
  EditEmail: undefined;
  EditAvatar: undefined;
  EditPhone: undefined;
  EditCpf: undefined;
  EditLocation: undefined;
  DeleteAccountStep1: undefined;
  DeleteAccountStep2: undefined;
  DeleteDependent: { dependentId: string };
  DeleteCard: { paymentMethodId: string };
};
